### ISSUE TITLE
Generate favicons per origin in multisite

### ISSUE THREAD

**Issue by marcorieser** [studio1902/statamic-peak-browser-appearance#7]
**Is your feature request related to a problem?**
Favicons (png) are currently generated from the default site.

**Describe the solution you'd like**
Favicons (png) are generated per origin site (have a look at the screenshot).

**Additional context**
Given a multisite setup where two separate websites live in the same Statamic instance. One for a movie project and the other for the production company. They come in different designs and should have different favicons too.
![Bildschirmfoto 2023-11-08 um 08 47 54](https://github.com/studio1902/statamic-peak-browser-appearance/assets/2395800/aab85c99-d594-4294-a62b-23268d343b87)

**Comment by robdekort** [comment]
The fields are not localisable by default, and I never knew you could overwrite this to be honest. I would say it's not intended to work this way, but I'd be happy to merge a PR.

**Comment by marcorieser** [comment]
I put it on my list 👍🏻

**Comment by robdekort** [comment]
Wonderful. Thank you!
